[package]
name = "keyring-lib"
description = "Cross-platform, sans I/O library to manage credentials"
version = "2.0.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["asynchronous"]
keywords = ["password", "credential", "keychain", "keyring", "secret"]
homepage = "https://pimalaya.org/"
documentation = "https://docs.rs/keyring-lib/latest/keyring/"
repository = "https://github.com/pimalaya/keyring/"

[package.metadata.docs.rs]
features = []
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "keyring"

[features]
default = []

# Linux Secret service, based on D-Bus
#
secret-service-dbus-std = ["dep:dbus"]
secret-service-dbus-openssl-std = ["dep:num", "dep:openssl", "dep:once_cell", "dep:rand", "secret-service-dbus-std"]
secret-service-dbus-rust-crypto-std = ["dep:aes", "dep:block-padding", "dep:cbc", "dep:hkdf", "dep:sha2", "secret-service-dbus-std"]

# MacOS/iOS Keychain
#
apple-native-std = ["dep:security-framework"]

# Windows Credentials
#
windows-native-std = ["dep:byteorder", "dep:windows-sys"]

# Vendored
#
vendored = ["dbus?/vendored", "openssl?/vendored"]

[build-dependencies]
dbus-codegen = { version = "0.12", default-features = false }

[dependencies]
secrecy = "0.10"
thiserror = "2"
tracing = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
aes = { version = "0.8", optional = true }
block-padding = { version = "0.3", features = ["std"], optional = true }
cbc = { version = "0.1", features = ["block-padding", "alloc"], optional = true }
dbus = { version = "0.9", optional = true }
hkdf = { version = "0.12", features = ["std"], optional = true }
num = { version = "0.4", optional = true }
once_cell = { version = "1", optional = true }
openssl = { version = "0.10", optional = true }
rand = { version = "0.8", optional = true }
sha2 = { version = "0.10", optional = true }

[target.'cfg(target_vendor = "apple")'.dependencies]
security-framework = { version = "3", default-features = false, optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
byteorder = { version = "1.2", optional = true }
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Security_Credentials"], optional = true }
