name: Examples

on:
  push:

jobs:
  apple-keychain-std:
    runs-on: ${{ matrix.macos }}
    strategy:
      fail-fast: false
      matrix:
        macos: [macos-13, macos-14, macos-15]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz
          enable_kvm: true
      - run: nix-shell -p nix-info --run "nix-info -m"
      - uses: cachix/cachix-action@v15
        with:
          name: soywod
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix-shell --run "cargo run -p keyring-apple-keychain-std --example entry"

  windows-credentials-std:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo run -p keyring-windows-credentials-std --example entry

  secret-service-dbus-std:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz
          enable_kvm: true
      - run: nix-shell -p nix-info --run "nix-info -m"
      - uses: cachix/cachix-action@v15
        with:
          name: soywod
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libdbus-1-dev libssl-dev gnome-keyring
      - run: gnome-keyring-daemon --components=secrets --daemonize --unlock <<< 'password'
      - run: nix-shell --run "cargo run -p keyring-secret-service-dbus-std --example entry"
