name: Run examples

on:
  push:

jobs:
  examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            features: secret-service-blocking,std
            example: secret-service-blocking-std
          - os: macos-13
            features: apple-native,std
            example: apple-std
          - os: windows-latest
            features: windows-native,std
            example: windows-std
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.os == 'ubuntu-latest'
        with:
          packages: libdbus-1-dev
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo run --features ${{ matrix.features }} --example ${{ matrix.example }}
